name = "langlib"
version = "0.1.0"
defaultTargets = ["Langlib"]
testDriver = "tests"

[[lean_lib]]
name = "Langlib"
globs = ["Langlib.**"]

[[lean_exe]]
name = "tests"
root = "Langlib.Tests.Main"

[[lean_exe]]
name = "brainfuck"
root = "Langlib.Languages.Brainfuck.Main"

[[lean_exe]]
name = "turpentine"
root = "Langlib.Turpentine.Main"

[[lean_exe]]
name = "fractran"
root = "Langlib.Languages.Fractran.Main"

[[lean_exe]]
name = "subleq"
root = "Langlib.Languages.Subleq.Main"

[[lean_exe]]
name = "whitespace"
root = "Langlib.Languages.Whitespace.Main"

[[lean_exe]]
name = "ook"
root = "Langlib.Languages.Ook.Main"

[[lean_exe]]
name = "deadfish"
root = "Langlib.Languages.Deadfish.Main"

[[lean_exe]]
name = "befunge93"
root = "Langlib.Languages.Befunge93.Main"

[[lean_exe]]
name = "thue"
root = "Langlib.Languages.Thue.Main"

[[lean_exe]]
name = "malbolge"
root = "Langlib.Languages.Malbolge.Main"

[[lean_exe]]
name = "piet"
root = "Langlib.Languages.Piet.Main"

[[lean_exe]]
name = "brainloller"
root = "Langlib.Languages.Brainloller.Main"
