import Langlib.Languages.JavaGen.Validation

/-!
# JavaGen: export to Java wildcard types

Type uses carry `? super`; the outer argument in an `extends` clause must
be invariant. Prefixed source names cannot collide with Java keywords,
the parameter `X`, the nullary `JG_Z` or the wrapper `JavaGenCheck`.
The exporter requires prepared input. Its correspondence is covered by
`scripts/javagen-conformance.py`, not yet by a Lean theorem.
-/

namespace Langlib.JavaGen

def javaUse (names : List String) (tail : String) : String :=
  names.foldr (fun name body => "JG_" ++ name ++ "<? super " ++ body ++ ">") tail

def javaBase (t : Template) : String :=
  let tail := match t.tail with | .var => "X" | .zero => "JG_Z"
  match t.ctors with
  | [] => tail
  | name :: rest => "JG_" ++ name ++ "<" ++ javaUse rest tail ++ ">"

private def javaDecl (d : Decl) : String :=
  "interface JG_" ++ d.name ++ "<X>" ++
    (if d.bases.isEmpty then "" else
      " extends " ++ String.intercalate ", " (d.bases.map javaBase)) ++ " {}\n"

/-- Declarations alone let conformance distinguish bad exports from rejected queries. -/
def exportJava (p : Prepared) (includeQuery : Bool := true) : String :=
  let declarations := "interface JG_Z {}\n" ++ String.join (p.source.classes.map javaDecl)
  let query := if includeQuery then
    "  " ++ javaUse p.source.query.rhs "JG_Z" ++ " check(" ++
      javaUse p.source.query.lhs "JG_Z" ++ " value) { return value; }\n"
    else ""
  "// Generated by LangLib JavaGen. Type-check this file; no JVM entry point.\n" ++
    declarations ++ "class JavaGenCheck {\n" ++ query ++ "}\n"

end Langlib.JavaGen
