#!/usr/bin/env python3
"""Generate finite arithmetic type recurrences, without computing their answers."""

import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEST = ROOT / "Langlib/Examples/JavaGen"


def app(names, tail="x"):
    for name in reversed(names):
        tail = f"{name}<{tail}>"
    return tail


def program(name, description, declarations, query):
    return (f"// {description}\n"
            "// Generated by scripts/gen-javagen-examples.py; no source evaluator was run.\n"
            f"// Usage: python3 scripts/javagen-certify.py Langlib/Examples/JavaGen/{name}.jgen\n"
            "zero Z;\ninterface Succ<x> {}\ninterface Pad<x> {}\n" +
            "\n".join(f"interface {n}<x> extends {body} {{}}" for n, body in declarations) +
            f"\ncheck {query}<Z> <: answer;\n")


def examples():
    fib = [("Fib1", "Succ<x>"), ("Fib2", "Succ<x>")]
    for n in range(3, 11):
        fib.append((f"Fib{n}", app([f"Fib{n-1}", "Pad", f"Fib{n-2}"])))
    yield "fib", program("fib", "The tenth Fibonacci number, mirroring fib-tc.turp.", fib, "Fib10")
    fact = [("Fact0", "Succ<x>")]
    for n in range(1, 6):
        terms = [item for _ in range(n) for item in [f"Fact{n-1}", "Pad"]][:-1]
        fact.append((f"Fact{n}", app(terms)))
    yield "fact", program("fact", "Factorial of five, mirroring fact-tc.turp.", fact, "Fact5")
    sums = [("Num1", "Succ<x>"), ("Sum1", "Succ<x>")]
    for n in range(2, 11):
        sums.extend([(f"Num{n}", app(["Num1", "Pad", f"Num{n-1}"])),
                     (f"Sum{n}", app([f"Sum{n-1}", "Pad", f"Num{n}"]))])
    yield "sum", program("sum", "Sum the numbers from one to ten by a type recurrence.", sums, "Sum10")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    failed = False
    for name, text in examples():
        path = DEST / f"{name}.jgen"
        if args.check:
            if not path.exists() or path.read_text() != text:
                print(f"stale: {path.relative_to(ROOT)}")
                failed = True
        else:
            path.write_text(text)
    return int(failed)


if __name__ == "__main__":
    raise SystemExit(main())
