import Langlib.Tests.JavaGenCompiler

/-! Regenerate original JavaGen compiler fixtures without evaluating their source. -/
open Langlib.JavaGen Langlib.Computability.JavaGen

def writeExample (check : Bool) (path : System.FilePath) (text : String) : IO Unit := do
  if check then
    unless (← IO.FS.readFile path) == text do
      throw (IO.userError s!"stale generated example: {path}")
  else
    if let some parent := path.parent then IO.FS.createDirAll parent
    IO.FS.writeFile path text

def main (args : List String) : IO Unit := do
  unless args == [] || args == ["--check"] do
    throw (IO.userError "usage: lake env lean --run scripts/gen-javagen-compiler-examples.lean [--check]")
  let check := args == ["--check"]
  let growthPath := "Langlib/Examples/JavaGen/grow.jgen"
  writeExample check growthPath ("// Generated by scripts/gen-javagen-compiler-examples.lean.\n" ++
    "// Each sweep duplicates every tape symbol; every finite fuel is exhausted.\n" ++
    "// Usage: lake exe javagen --fuel 100 " ++ growthPath ++ "\n" ++ Growth.source.render)
  for (name, code, bound, _) in Langlib.Tests.JavaGenCompiler.examples do
    match CounterCompiler.compileFlow (CounterCompiler.counterFlow code) bound with
    | .error e => throw (IO.userError e)
    | .ok p =>
      let path := s!"Langlib/Examples/JavaGen/compiled/{name}.jgen"
      writeExample check path ("// Generated by scripts/gen-javagen-compiler-examples.lean.\n" ++
        "// Closed subtype execution prints a proof record; numeric answer certification is pending for this compiler.\n" ++
        s!"// Usage: lake exe javagen --fuel 10000 {path}\n" ++ p.source.render)
